// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAtoZ8q1SULBeQBkqOwmMqoPjtrv7S480',
    appId: '1:789825864830:web:5a4d27402fee97596ec42f',
    messagingSenderId: '789825864830',
    projectId: 'ostad-dec17',
    authDomain: 'ostad-dec17.firebaseapp.com',
    storageBucket: 'ostad-dec17.appspot.com',
    measurementId: 'G-2HRG85JSZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfCGIn3ObdcxbKrUqaT7sNU62wPDFNqrQ',
    appId: '1:789825864830:android:9aa4911850179ec16ec42f',
    messagingSenderId: '789825864830',
    projectId: 'ostad-dec17',
    storageBucket: 'ostad-dec17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5R_7BYustsJQDKhcVn1WQwAyH5SP8w7Q',
    appId: '1:789825864830:ios:94d040b12d83cbc26ec42f',
    messagingSenderId: '789825864830',
    projectId: 'ostad-dec17',
    storageBucket: 'ostad-dec17.appspot.com',
    iosBundleId: 'com.example.firebaseAndMap',
  );
}
